apiVersion: v1
kind: Namespace
metadata:
  name: carserv          # workload + predictor + KEDA ScaledObject
  labels:
    name: carserv
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring       # prometheus, grafana, pushgateway, kube-state-metrics, haproxy
  labels:
    name: monitoring
